<a href="https://colab.research.google.com/github/NikhithaPatibandla/ML-CourseWork/blob/main/Week_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#Importing the necessary libraries
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [28]:
#create 2 arrays using numpy
x = np.array([10,10,10,10,10,10,10,10,10,10]).reshape(-1,1)
y = np.array([0,0,0,0,1,1,1,1,1,1])

In [29]:
#Create a logistic regression model
model = LogisticRegression(solver='liblinear',random_state=0)
model.fit(x,y)

LogisticRegression(random_state=0, solver='liblinear')

In [30]:
model = LogisticRegression(solver='liblinear',random_state=0).fit(x,y)

In [31]:
#Prints the classes of the model
model.classes_

array([0, 1])

In [32]:
#Prints the intercept of the model
model.intercept_

array([0.00399799])

In [33]:
#Prints the coefficient of the model
model.coef_

array([[0.03997987]])

In [34]:
#Predicts the probabilities
model.predict_proba(x)

array([[0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952],
       [0.40040048, 0.59959952]])

In [35]:
#Predicts the x value
model.predict(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
#Prints how strong the relationship between x and y is from 0 to 1
model.score(x,y)

0.6

In [37]:
#Gives th confusion matrix
confusion_matrix(y,model.predict(x))

array([[0, 4],
       [0, 6]])

In [38]:
#Prints the classification report
print(classification_report(y,model.predict(x)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.60      1.00      0.75         6

    accuracy                           0.60        10
   macro avg       0.30      0.50      0.38        10
weighted avg       0.36      0.60      0.45        10



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [39]:
#Improve the model
model = LogisticRegression(solver='liblinear',C=10.0,random_state=0).fit(x,y)

In [40]:

model.classes_

array([0, 1])

In [41]:
model.intercept_

array([0.00401282])

In [42]:
model.coef_

array([[0.04012821]])

In [43]:
model.predict_proba(x)

array([[0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916],
       [0.40004084, 0.59995916]])

In [44]:
model.predict(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
model.score(x,y)

0.6

In [46]:
confusion_matrix(y,model.predict(x))

array([[0, 4],
       [0, 6]])

In [47]:
print(classification_report(y,model.predict(x)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.60      1.00      0.75         6

    accuracy                           0.60        10
   macro avg       0.30      0.50      0.38        10
weighted avg       0.36      0.60      0.45        10



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
